<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orion.Configuration\Orion.Configuration.csproj" />
    <ProjectReference Include="..\Orion.JsonParser\Orion.JsonParser.csproj" />
    <ProjectReference Include="..\Orion.Models\Orion.Models.csproj" />
  </ItemGroup>

</Project>
