// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orion.Server.DataLayer;

#nullable disable

namespace Orion.Server.Migrations
{
    [DbContext(typeof(OrionDbContext))]
    [Migration("20241126191234_Roles")]
    partial class Roles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DirectCommunicationUser", b =>
                {
                    b.Property<Guid>("DirectCommunicationsDirectCommunicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MembersUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DirectCommunicationsDirectCommunicationId", "MembersUserId");

                    b.HasIndex("MembersUserId");

                    b.ToTable("DirectCommunicationUser");
                });

            modelBuilder.Entity("Orion.Server.DirectCommuncations.DirectCommunication", b =>
                {
                    b.Property<Guid>("DirectCommunicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DirectCommunicationId");

                    b.ToTable("DirectCommunications");
                });

            modelBuilder.Entity("Orion.Server.Messages.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DirectCommunicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MessageId");

                    b.HasIndex("DirectCommunicationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Orion.Server.Users.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DirectCommunicationUser", b =>
                {
                    b.HasOne("Orion.Server.DirectCommuncations.DirectCommunication", null)
                        .WithMany()
                        .HasForeignKey("DirectCommunicationsDirectCommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orion.Server.Users.User", null)
                        .WithMany()
                        .HasForeignKey("MembersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orion.Server.Messages.Message", b =>
                {
                    b.HasOne("Orion.Server.DirectCommuncations.DirectCommunication", null)
                        .WithMany("Messages")
                        .HasForeignKey("DirectCommunicationId");

                    b.HasOne("Orion.Server.Users.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Orion.Server.DirectCommuncations.DirectCommunication", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
